import { mockNaruto } from './mockCharacter/mockNaruto';
import { mockNorogami } from './mockCharacter/mockNorogami';
import { mockTokyoghoul } from './mockCharacter/mockTokyoghoul';
import { AnimeType } from './type/typeAnime';

export const mockAnime: AnimeType[] = [
  {
    id: 0,
    title: 'Noragami',
    studio: 'Bones',
    year: 2014,
    genres: ['Action', 'Supernatural', 'Fantasy'],
    img: './img/cardanime/noragami.png',
    posterImg: './img/person/norogami/yato-full.png',
    characters: mockNorogami,
  },
  {
    id: 1,
    title: 'Naruto',
    studio: 'Studio Pierrot',
    year: 2002,
    genres: ['Adventure', 'Comedy', 'Fantasy'],
    img: './img/cardanime/naruto.png',
    characters: mockNaruto,
  },
  {
    id: 2,
    title: 'Bleach',
    studio: 'Studio Pierrot',
    year: 2004,
    genres: ['Adventure', 'Supernatural'],
    img: './img/cardanime/bleach.png',
  },
  {
    id: 3,
    title: 'Tokyo Ghoul',
    studio: 'Studio Pierrot',
    year: 2014,
    genres: ['Supernatural', 'Fantasy'],
    img: './img/cardanime/tokyoghole.jpg',
    characters: mockTokyoghoul,
  },
  {
    id: 4,
    title: 'Another',
    studio: 'P.A. Works',
    year: 2012,
    genres: ['Horror', 'Supernatural'],
    img: './img/cardanime/Another.jpg',
  },
  {
    id: 5,
    title: 'Sen to Chihiro no Kamikakushi',
    studio: 'Studio Ghibli',
    year: 2001,
    genres: ['meow'],
    img: './img/cardanime/SentoChihironoKamikakushi.jpg',
  },
  {
    id: 6,
    title: 'Howl no Ugoku Shiro',
    studio: 'Studio Ghibli',
    year: 2004,
    genres: ['meow'],
    img: './img/cardanime/HowlnoUgokuShiro.jpg',
  },
  {
    id: 7,
    title: 'Mononoke Hime',
    studio: 'Studio Ghibli',
    year: 1997,
    genres: ['meow'],
    img: './img/cardanime/MononokeHime.jpg',
  },
  {
    id: 8,
    title: 'Gake no Ue no Ponyo',
    studio: 'Studio Ghibli',
    year: 2008,
    genres: ['meow'],
    img: './img/cardanime/GakenoUenoPonyo.jpg',
  },
  {
    id: 9,
    title: 'Fullmetal Alchemist: Brotherhood',
    studio: 'Bones Animation Studios',
    year: 2009,
    genres: ['meow'],
    img: './img/cardanime/FullmetalAlchemistBrotherhood.jpg',
  },
  {
    id: 10,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    studio: 'Ufotable',
    year: 2019,
    genres: ['meow'],
    img: './img/cardanime/DemonSlayerKimetsunoYaiba.jpg',
  },
  {
    id: 11,
    title: 'Mo Dao Zu Shi',
    studio: 'Tencent Penguin Pictures',
    year: 2018,
    genres: ['meow'],
    img: './img/cardanime/MoDaoZuShi.jpg',
  },
  {
    id: 12,
    title: 'Jujutsu Kaisen',
    studio: 'Studio MAPPA',
    year: 2020,
    genres: ['meow'],
    img: './img/cardanime/JujutsuKaisen.jpg',
  },
  {
    id: 13,
    title: 'Bocchi the Rock!',
    studio: 'CloverWorks',
    year: 2022,
    genres: ['meow'],
    img: './img/cardanime/BocchitheRock.jpg',
  },
];
